ALTER TABLE outlets DISABLE ROW LEVEL SECURITY;
ALTER TABLE pelanggan DISABLE ROW LEVEL SECURITY;
ALTER TABLE layanan DISABLE ROW LEVEL SECURITY;
ALTER TABLE antrian DISABLE ROW LEVEL SECURITY;
ALTER TABLE karyawan DISABLE ROW LEVEL SECURITY;